### ISSUE TITLE
Empty result

### ISSUE THREAD

**Issue by K0walski777** [fnep/aplot#7]
Hi!
When starting `python3 aplot table -p /path/to/atop_yyyymmdd CPL.avg5` I receive messages "empty result".
What could be the problem?

**Comment by K0walski777** [comment]
I using atop-2.4

**Comment by fnep** [comment]
Thank you for reporting this. The project is not actively maintained as stated in the readme. I’m not sure when I will have time to have a look into it. 

Are you interested in submitting a pull request?
